In [1]:
# Import necessary modules
import numpy as np
import pandas as pd
import cv2 as cv2

Feed the image

In [2]:
image_location = "./images/indian_cricket_team.webp"
original_image = cv2.imread(image_location)
# cv2.imshow("Fed image", original_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Use face cascade classifier

In [3]:
"""
We will use the 'haarcascade_frontalface_default' classifier and feed the image to it.
'detectMultiScale2' returns two values:
    i) The coordinates of the face(s) on the image
    ii) Minimum number of neighbours
"""

face_cascade = cv2.CascadeClassifier("./cascade_classifier/haarcascade_frontalface_default.xml")
face_coordinates, min_neighbours = face_cascade.detectMultiScale2(original_image, minNeighbors=10)

Check the outputs from detectMultiscale

In [7]:
# print(f"Image attributes:\n{face_coordinates}\n")
# print(f"Image neighbours:\n{min_neighbours}")

Image attributes:
[[ 15   9  57  57]
 [470  15  61  61]
 [163  28  52  52]
 [372  31  48  48]
 [266  33  46  46]]

Image neighbours:
[40 32 31 30 11]


Draw a square around the detected face

In [5]:
for x_coordinate, y_coordinate, width, height in face_coordinates:
    cv2.rectangle(original_image, (x_coordinate, y_coordinate), (x_coordinate + width, y_coordinate + height), (0, 0, 255))
cv2.imshow("Face detected", original_image)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>